# 1. 
 
Write a function to compute 5/0 and use try/except to catch the exceptions. # 

In [5]:

def firstexception():
    try:
        calc=5/0
    except ZeroDivisionError as e:
        return print("Be careful it is ZeroDivisionError")
firstexception()

Be careful it is ZeroDivisionError


# 2. 
 
Implement a Python program to generate all sentences where subject is in ["Americans", "Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"]. 
 
Hint: Subject,Verb and Object should be declared in the program as shown below. 
 
subjects=["Americans ","Indians"] verbs=["play","watch"] objects=["Baseball","Cricket"] 
 
Output should come as below: 
 
Americans  play Baseball. Americans  play Cricket. Americans  watch Baseball. Americans  watch Cricket. Indians play Baseball. Indians play Cricket. Indians watch Baseball. Indians watch Cricket.  

In [6]:
subject =["Americans", "Indians"]
verb = ["Play", "watch"]
object = ["Baseball","cricket"]
for a in subject:
    for b in verb:
        for c in object:
            print(f'{a} {b} {c}.')

Americans Play Baseball.
Americans Play cricket.
Americans watch Baseball.
Americans watch cricket.
Indians Play Baseball.
Indians Play cricket.
Indians watch Baseball.
Indians watch cricket.


#  Task 2:
1.
Write a function so that the columns of the output matrix are powers of the input vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

HINT: Such a matrix with a geometric progression in each row is named for AlexandreTheophile Vandermonde.
NOTE: The solution shared through Github should c

In [7]:
import numpy as np
num=[2,3,5,6]
N=4
result=np.vander(num,N,increasing=False)
print(result)

[[  8   4   2   1]
 [ 27   9   3   1]
 [125  25   5   1]
 [216  36   6   1]]
